baseURL = "https://artikelkknlima.netlify.app/"
languageCode = "id-ID"
title = "KKN Kelompok 5 Sragen Tengah"

[params]
  description = "Portal Berita Kegiatan KKN Kelompok 5 Sragen Tengah"
  author = "Kelompok 5"